### ISSUE TITLE
Tiling issue with asset id: 11211

### ISSUE THREAD

**Issue by sksun** [AnalyticalGraphicsInc/cesium-ion-community#62]
<Please provide a short summary of your data.>

**Comment by lilleyse** [comment]
Hi @sksun it looks like this is related to https://github.com/AnalyticalGraphicsInc/cesium-ion-community/issues/58 which also fails during geometry compression. Thanks for the report.

**Comment by lilleyse** [comment]
Hi @sksun, this problem has been fixed in ion. Thanks again!

**Comment by sksun** [comment]
Dear Sean

Thanks for your help.
Still have problem with other dataset
Tiling issue with asset id: 12248



B. R.

Kevin Sun 孫樹國 博士
CEO 總經理
Omniguider Inc. 鴻圖股份有限公司
Tel:+886-2-5569-1686 ext. 13905 
Mobile: +886-920-053-114 

寄件者: Sean Lilley
傳送時間: 2018年12月11日 下午 09:44
收件者: AnalyticalGraphicsInc/cesium-ion-community
副本: sksun; Mention
主旨: Re: [AnalyticalGraphicsInc/cesium-ion-community] Tiling issue withasset id: 11211 (#62)

Hi @sksun, this problem has been fixed in ion. Thanks again!

**Comment by hpinkos** [comment]
Thanks @sksun, I've opened a new issue for Asset 12248 so we can track the bug and let you know when it's fixed: #72
